module.exports = [
  'backup-app-settings',
  'backup-all-forms',
  'compile-app-settings',
  'compress-images',
  'convert-app-forms',
  'convert-contact-forms',
  'delete-all-forms',
  'initialise-project-layout',
  'upload-app-forms',
  'upload-app-settings',
  'upload-collect-forms',
  'upload-contact-forms',
  'upload-resources',
  'upload-custom-translations',
];
