#!/bin/bash -eu

versions() {
	git tag | grep '^v' | sort --field-separator=. --key=1,1nr --key=2,2nr --key=3,3nr
}

changelog() {
	local previous="$1"
	local currentTree="$2"
	local currentName="$3"
	echo "## $currentName"
	git log "${previous}..${currentTree}" --pretty=oneline | cut -d' ' -f2- | sed -E -e 's/^/* /'
	echo
}

echo "# Changelog"
echo

current=""
for previous in $(versions); do
	if [[ -z "$current" ]]; then
		changelog "$previous" master "v$(jq -r .version package.json)"
	else
		changelog "$previous" "$current" "$current"
	fi
	current="$previous"
done
