#!/bin/bash -eu

versions() {
	git tag | grep '^v' | sort --field-separator=. --key=1,1nr --key=2,2nr --key=3,3nr
}

changelog() {
	local previous="$1"
	local currentTree="$2"
	local currentName="$3"

	if [[ "$currentName" == "$previous" ]]; then
		local currentName="master"
		local released=""
	else
		local released=`git log -1 --pretty=format:"%ad" --date=short $currentName 2> /dev/null`
	fi

	echo "## [\`$currentName\`](https://github.com/medic/medic-conf/tree/$currentName)"
	echo
	if [[ -z "$released" ]]; then
		echo "...not yet released..."
	else
		echo "Released: $released"
	fi
	echo
	git log "${previous}..${currentTree}" --pretty=oneline --abbrev-commit | sed -E -e \
		's/^([a-z0-9]{7}) /* [\`\1\`](https:\/\/github.com\/medic\/medic-conf\/commit\/\1) /'
	echo
}

echo "# Changelog"
echo

current=""
for previous in $(versions); do
	if [[ -z "$current" ]]; then
		changelog "$previous" master "v$(jq -r .version package.json)"
	else
		changelog "$previous" "$current" "$current"
	fi
	current="$previous"
done
changelog initial "$current" "$current"
